### PR TITLE
[WIP] Update NServiceBus 6.1.0

### PR DESCRIPTION
**Pull request by danielmarbach**
Relates to https://github.com/Particular/NServiceBus/pull/4377

Smoke tests SC plugin against 6.1 (currently contains RC1, we can then update this PR when 6.1 final is released)

### CODE REVIEW

**Comment by timbussmann** [comment]
@Particular/servicecontrol-maintainers 6.1 is now officially released. Feel free to pick up this PR and update it to the final 6.1 package. It's up to you whether you decide to only update the test projects or if you update the main projects build dependency to 6.1 too. In case of the second option, please be careful to update nuspec dependencies only if you make use of newly available 6.1 APIs.

**Comment by gbiellem** [comment]
@timbussmann  @danielmarbach Why is this being bumped to 6.1?  These isn't what we've done with the V5 and V4 plugins.  They were left targeting the original major.

**Comment by timbussmann** [comment]
@gbiellem this was mainly done as a smoke test for the v6.1 release to check nothing was accidentally broken. We recommend to not update the main project indeed, but many downstreams want to have the improvements in the acceptance tests provided by 6.1. Entirely up to the maintainers to:
* Ignore the 6.1 release entirely (close this PR)
* Update only the acceptance tests to use 6.1 (modify this PR, but shouldn't apply for this repo anyway)
* Update everything to 6.1

I hope this makes the intention of this PR clearer.

**Comment by gbiellem** [comment]
Thanks @timbussmann, that makes sense.

**Pull request closed without merging**
